[workspace]
members = [
  "crates/v64-capi",
  "crates/v64-cli",
  "crates/v64-core",
  "apps/v64-player",
  "apps/video64-drop-native",
  "crates/v64-wasm",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"
repository = "https://github.com/ShaelRiley/v64"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
